import { expect, test } from "@playwright/test";
import { createHistory, commit, redo, undo } from "../src/lib/room-planner/history";
import { materializeVariant, type PlanVariant } from "../src/lib/room-planner/variants";
import { createProject, parseProject } from "../src/lib/room-planner/projects";
import { analyzeCurrentPlan } from "../src/lib/room-planner/currentPlanAnalysis";
import { BAVSTAETTV_REFERENCE } from "../src/lib/room-planner/rules/profiles";
import { DEFAULT_SEATING_RULES, type SeatingPlan } from "../src/lib/room-planner/seating";
import { moveSeat } from "../src/lib/room-planner/seatingEditing";
import type { RoomPlan } from "../src/lib/room-planner/objects";

test("WP16.5A materialized auto objects share history, storage and live rule evaluation", () => {
  const seats = [{ id: "seat-1", x: 2, y: 2, rotation: 0, row: 1, index: 1 }];
  const seating: SeatingPlan = { blocks: [{ id: "block-1", seats, rowCount: 1, seatsPerRow: [1] }], seats, totalSeats: 1, totalRows: 1, longestRow: 1, hints: [], rules: { ...DEFAULT_SEATING_RULES }, orientation: "horizontal" };
  const base: RoomPlan = { contour: { closed: true, points: [{ id: "a", x: 0, y: 0 }, { id: "b", x: 10, y: 0 }, { id: "c", x: 10, y: 10 }, { id: "d", x: 0, y: 10 }], walls: [{ id: "w1", startPointId: "a", endPointId: "b" }, { id: "w2", startPointId: "b", endPointId: "c" }, { id: "w3", startPointId: "c", endPointId: "d" }, { id: "w4", startPointId: "d", endPointId: "a" }] }, objects: [{ id: "exit", type: "door", wallId: "w1", offset: 2, width: 1.2, role: "exit", clearWidth: 1.2 }] };
  const aisle = { id: "auto-aisle", type: "aisle" as const, source: "generated" as const, start: { x: 3, y: 1 }, end: { x: 3, y: 9 }, width: 1.2 };
  const variant = { plan: { ...base, objects: [...base.objects, aisle] }, seatingPlan: seating } as PlanVariant;
  const adopted = materializeVariant(variant);
  expect(adopted.objects).toContainEqual(aisle);
  expect(adopted.seating.blocks[0].source).toBe("generated");
  expect(moveSeat(adopted, adopted.seating, "seat-1", .1, 0).seating.seats[0].x).toBe(2.1);
  const deduplicated = materializeVariant({ ...variant, plan: { ...variant.plan, objects: [...variant.plan.objects, { ...aisle }] } });
  expect(new Set(deduplicated.objects.map((object) => object.id)).size).toBe(deduplicated.objects.length);
  const moved = { ...adopted, objects: adopted.objects.map((object) => object.id === aisle.id ? { ...aisle, start: { x: 4, y: 1 }, end: { x: 4, y: 9 }, width: .8, edited: true } : object) };
  const history = commit(commit(createHistory(base), adopted), moved);
  expect(undo(history).present).toBe(adopted);
  expect(redo(undo(history)).present).toBe(moved);
  expect(parseProject(JSON.stringify(createProject("Auto", moved))).plan.objects).toEqual(moved.objects);
  expect(analyzeCurrentPlan(moved, seating, BAVSTAETTV_REFERENCE).report.checks.some((check) => check.ruleId === "aisle-width" && check.status === "fail")).toBe(true);
  const deleted = { ...moved, objects: moved.objects.filter((object) => object.id !== aisle.id) };
  const afterDelete = commit(history, deleted);
  expect(undo(afterDelete).present).toBe(moved);
  expect(redo(undo(afterDelete)).present.objects.some((object) => object.id === aisle.id)).toBe(false);
  expect(parseProject(JSON.stringify(createProject("Deleted", deleted))).plan.objects.some((object) => object.id === aisle.id)).toBe(false);
  expect(analyzeCurrentPlan(deleted, seating, BAVSTAETTV_REFERENCE).report.checks.some((check) => check.id === "aisles-missing" && check.status === "fail")).toBe(true);
});

test("WP16.5A preview auto aisle becomes editable and survives reload and delete", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/raumplaner");
  const editor = page.getByRole("region", { name: "2D-Grundrisseditor" });
  const svg = editor.getByRole("img", { name: "Grundriss Zeichenfläche" });
  const box = (await svg.boundingBox())!;
  const left = box.width / 2 - 225, top = box.height / 2 - 180;
  const click = (x: number, y: number) => svg.click({ position: { x, y } });
  await click(left, top); await click(left + 450, top); await click(left + 450, top + 360); await click(left, top + 360); await click(left, top);
  await editor.getByRole("button", { name: "Tür", exact: true }).click();
  await click(left + 45, top);
  await editor.getByLabel("Türrolle").selectOption("exit");
  await editor.getByRole("button", { name: "Gang", exact: true }).click();
  await click(left + 45, top + 32); await click(left + 45, top + 328);
  await editor.getByRole("button", { name: "Planvarianten berechnen" }).click();
  const variants = editor.getByLabel("Planvarianten");
  await expect(variants.getByText(/Kandidaten mit dem gewählten Regelprofil geprüft/)).toBeVisible({ timeout: 30000 });
  await editor.getByRole("button", { name: "Auswahl" }).click();
  let preview = svg.locator('polygon[data-object-id][fill="#df9a45"]').first();
  for (const name of ["Ausgewogen", "Kapazität", "Komfort"]) {
    if (await preview.count()) break;
    await variants.getByRole("button", { name: new RegExp(`^${name}`) }).click();
    preview = svg.locator('polygon[data-object-id][fill="#df9a45"]').first();
  }
  await expect(preview).toBeVisible();
  const id = await preview.getAttribute("data-object-id");
  await preview.click();
  const properties = editor.getByLabel("Eigenschaften");
  await expect(properties.getByText(/Quelle: automatisch/)).toBeVisible();
  const aisle = svg.locator(`polygon[data-object-id="${id}"]`);
  const dragBox = (await aisle.boundingBox())!;
  const dragX = dragBox.x + dragBox.width / 2, dragY = dragBox.y + dragBox.height / 2;
  const beforeDrag = await properties.getByLabel("Start X (m)").inputValue();
  await page.mouse.move(dragX, dragY);
  await page.mouse.down(); await page.mouse.move(dragX + 9, dragY, { steps: 4 }); await page.mouse.up();
  await expect.poll(() => properties.getByLabel("Start X (m)").inputValue()).not.toBe(beforeDrag);
  const before = await properties.getByLabel("Start X (m)").inputValue();
  await properties.getByLabel("Start X (m)").fill(String(Number(before) + .2));
  await expect(properties.getByText(/bearbeitet/)).toBeVisible();
  await properties.getByLabel("Breite (m)").fill("0.8");
  await properties.getByLabel("Breite (m)").press("Tab");
  await properties.getByLabel("Länge (m)").fill("3");
  await properties.getByLabel("Länge (m)").press("Tab");
  await expect(properties.getByLabel("Länge (m)")).toHaveValue("3");
  await expect(properties.getByText(/rechnerisch erforderlich/).first()).toBeVisible();
  await page.reload();
  await editor.getByRole("button", { name: "Auswahl" }).click();
  await svg.locator(`polygon[data-object-id="${id}"]`).click();
  await expect(properties.getByLabel("Breite (m)")).toHaveValue("0.8");
  await expect(properties.getByLabel("Länge (m)")).toHaveValue("3");
  await editor.getByRole("button", { name: "3D", exact: true }).click();
  await expect(editor.getByLabel("3D-Raumansicht").locator("canvas")).toBeVisible();
  await editor.getByRole("button", { name: "2D", exact: true }).click();
  await expect(svg.locator(`polygon[data-object-id="${id}"]`)).toHaveCount(1);
  await editor.getByLabel("Bestuhlung").getByLabel("Max. Stühle pro Reihe").fill("11");
  await expect(properties.getByLabel("Breite (m)")).toHaveValue("0.8");
  await editor.getByRole("button", { name: "Plan ausgeben" }).click();
  await expect(page.getByRole("region", { name: "Plan-Ausgabe" }).locator("svg text").filter({ hasText: "0,80 m" }).first()).toBeVisible();
  await page.getByRole("button", { name: "Zurück zum Editor" }).click();
  await svg.locator(`polygon[data-object-id="${id}"]`).click();
  await page.keyboard.press("Delete");
  await expect(svg.locator(`polygon[data-object-id="${id}"]`)).toHaveCount(0);
  await editor.getByRole("button", { name: "Rückgängig" }).click();
  await svg.locator(`polygon[data-object-id="${id}"]`).click();
  await properties.getByRole("button", { name: "Objekt löschen" }).click();
  await expect(svg.locator(`polygon[data-object-id="${id}"]`)).toHaveCount(0);
  await editor.getByRole("button", { name: "Rückgängig" }).click();
  await expect(svg.locator(`polygon[data-object-id="${id}"]`)).toHaveCount(1);
  await editor.getByRole("button", { name: "Wiederholen" }).click();
  await expect(svg.locator(`polygon[data-object-id="${id}"]`)).toHaveCount(0);
  await page.reload();
  await expect(svg.locator(`polygon[data-object-id="${id}"]`)).toHaveCount(0);
  await editor.getByRole("button", { name: "Plan ausgeben" }).click();
  await expect(page.getByRole("region", { name: "Plan-Ausgabe" }).locator('svg polygon[fill="#a9d2d8"]')).toHaveCount(1);
  expect(await aisle.count()).toBe(0);
});

test("WP16.5A calculated seating can be adopted through a block click", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/raumplaner");
  const editor = page.getByRole("region", { name: "2D-Grundrisseditor" });
  const svg = editor.getByRole("img", { name: "Grundriss Zeichenfläche" });
  const box = (await svg.boundingBox())!;
  const left = box.width / 2 - 180, top = box.height / 2 - 140;
  const click = (x: number, y: number) => svg.click({ position: { x, y } });
  await click(left, top); await click(left + 360, top); await click(left + 360, top + 280); await click(left, top + 280); await click(left, top);
  await editor.getByRole("button", { name: "Bestuhlung berechnen" }).click();
  await expect(editor.getByRole("button", { name: "Bestuhlung übernehmen und bearbeiten" })).toBeVisible();
  await editor.getByRole("button", { name: "Auswahl" }).click();
  await svg.locator("[data-block-id]").first().click({ position: { x: 10, y: 10 } });
  await expect(editor.getByLabel("Eigenschaften").getByText(/Sitzblock block-/)).toBeVisible();
  await expect(editor.getByRole("button", { name: "Bestuhlung übernehmen und bearbeiten" })).toHaveCount(0);
  await svg.locator("[data-seat-id]").first().click({ modifiers: ["Alt"] });
  const seatY = editor.getByLabel("Eigenschaften").getByLabel("Sitz Y (m)");
  await expect(seatY).toBeVisible();
  const originalY = Number(await seatY.inputValue());
  await seatY.fill(String(originalY + .05)); await seatY.press("Tab");
  await expect(seatY).toHaveValue(String(Number((originalY + .05).toFixed(4))));
  await editor.getByRole("button", { name: "Rückgängig" }).click();
  await editor.getByRole("button", { name: "Rückgängig" }).click();
  await expect(svg.locator("[data-block-id]")).toHaveCount(0);
  await editor.getByRole("button", { name: "Wiederholen" }).click();
  await expect(svg.locator("[data-block-id]").first()).toBeVisible();
  await page.reload();
  await expect(svg.locator("[data-block-id]").first()).toBeVisible();
});
